const XLSX = require('xlsx');
const wb = XLSX.utils.book_new();
const ws = XLSX.utils.aoa_to_sheet([['Date'], [new Date('2026-03-08T00:00:00Z')]]);
XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
const wb2 = XLSX.read(buf, { type: 'buffer', cellDates: true });
const ws2 = wb2.Sheets['Sheet1'];
const json = XLSX.utils.sheet_to_json(ws2);
console.log(json[0].Date);
console.log(json[0].Date.toISOString());
console.log(json[0].Date.getHours());
console.log(json[0].Date.getUTCHours());
